# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: client
output: models.gen.go
generate: 
  models: true
#compatibility: {}
output-options:
  name-normalizer: ToCamelCase
#import-mapping: {}
